[[main]]
identifier = 'home'
name = 'Home'
pre = "<i class='icon icon-home'></i>"
url = '/'
weight = 1

[[main]]
identifier = 'docs'
name = 'Documentation'
pre = "<i class='icon icon-book'></i>"
url = '/docs/'
weight = 2

[[main]]
identifier = 'about'
name = 'About'
pre = "<i class='icon icon-info'></i>"
url = '/about/'
weight = 3