description = 'A modular Hugo theme to build your next documentation site'

author = 'Your Name'
authorURL = 'https://your-site.com/'

facebookURL = 'https://facebook.com/'
twitterURL = 'https://www.twitter.com/'
githubURL = 'https://github.com/'
youtubeURL = 'https://www.youtube.com/'

githubRepo = 'your/repo'
githubSponsorURL = 'https://github.com/sponsors/'
buyMeACoffeeURL = 'https://www.buymeacoffee.com/'

hugoURL = 'https://gohugo.io/'
docuraURL = 'https://docura.github.io/'

[algolia]
[algolia.en]
container = '#site-header-search'
appId = ''
indexName = ''
apiKey = ''
