description = 'The Hugo documentation theme for your next project.'

author = 'Dumindu Madunuwan'
authorURL = 'https://github.com/dumindu'

facebookURL = 'https://facebook.com/doctura'
twitterURL = 'https://www.twitter.com/'
githubURL = 'https://github.com/doctura/site'
youtubeURL = 'https://www.youtube.com/'

githubRepo = 'doctura/site'
githubSponsorURL = 'https://github.com/sponsors/dumindu'
buyMeACoffeeURL = 'https://www.buymeacoffee.com/dumindu'

hugoURL = 'https://gohugo.io/'
docturaURL = 'https://doctura.github.io/'

[algolia]
[algolia.en]
container = '#site-header-search'
appId = 'doctura'
indexName = 'doctura'
apiKey = ''
