description = 'The documentation theme for your Hugo project.'

author = 'Dumindu Madunuwan'
authorURL = 'https://github.com/dumindu'

facebookURL = 'https://facebook.com/doctura'
twitterURL = ''
githubURL = 'https://github.com/doctura/site'
youtubeURL = ''

githubSponsorURL = 'https://github.com/sponsors/dumindu'
buyMeACoffeeURL = 'https://www.buymeacoffee.com/dumindu'

hugoURL = 'https://gohugo.io/'
docturaURL = 'https://doctura.github.io/'

[algolia]
[algolia.en]
container = '#site-header-search'
appId = 'doctura'
indexName = 'doctura'
apiKey = ''
